### ISSUE TITLE
E22..

### ISSUE THREAD

**Issue by narcomerk19** [samdenty99/Wi-PWN#20]
The error E22 is always showing after I start Attacking..

**Comment by samdenty99** [comment]
Which version of Wi-PWN are you using?

**Comment by VBIralo** [comment]
9.0Thanks 18.09.2017, 19:56, "Sam Denty" <notifications@github.com>:Which version of Wi-PWN are you using?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by narcomerk19** [comment]
Im using version 9.0 of your Wi-PWN.
and the boot verion was v.31_m.1, sdk v.1.3.0

**Comment by narcomerk19** [comment]
@samdenty99
 Version 9.0 is the latest version right sir ?

**Comment by samdenty99** [comment]
@narcomerk19 Version 9.0 is the latest preview version yes

*I'm not actively developing Wi-PWN at the moment, I may do a bit in a few weeks (it depends though)*

**Comment by StijnSimons** [comment]
@narcomerk19 are you sure your antenna isn't damage and you're not far from the NodeMCU.
If this won't resolve the issue, join the [discord](https://discordapp.com/invite/yN2x7sp) for a teamviewer session / debug session.

**Comment by StijnSimons** [comment]
Closing this for now. If this didn't solve your problem, reopen the issue.

**Comment by narcomerk19** [comment]
I only encounter this issue in this build, I like your work coz of the material inspired 🙂
hoping to fix that bug.. my node was fully working and does not have any damage..

**Comment by samdenty99** [comment]
@narcomerk19 In order to fully understand what is happening, could you please provide: 

What [version of Wi-PWN](https://github.com/samdenty99/Wi-PWN/releases) are you using? on which operating system & browser? And what are the exact steps you are doing when you face this issue? Does the attack start (LED turn on), and are you able to reconnect after?

Also, are you using the WiFi client feature? or the hotspot mode. This is a limitation of the WiFi client feature if you are

It would also be helpful if you could provide the **console output** <kbd>CTRL-SHIFT-I</kbd> → <kbd>Console</kbd>

**Comment by samdenty99** [comment]
Try cloning the repo and flashing with Arduino, the binary in the `arduino` folder is of an older version, and is causing this issue
